/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 volk_te-37_rim.glb 
Author: lukejdavis3 (https://sketchfab.com/lukejdavis3)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/volk-te-37-rim-0b0e2fe6a72d4801b454d94aaa4ac569
Title: Volk Te-37 Rim
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Volk_Te37(props) {
  const { nodes, materials } = useGLTF('models/volk_te-37_rim.glb')
  return (
    <group {...props} dispose={null}>
      {/* front right */}
      <group rotation={[-Math.PI / 2, 0, -0.93]} scale={2.23} position={[0.5, -0.415, 2.43]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      {/* back right */}
      <group rotation={[-Math.PI / 2, 0, -0.85]} scale={2.23} position={[-2.16, -0.42, -0.866]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      <group rotation={[-Math.PI / 2, 0, 2.25]} scale={2.23} position={[2.245, -0.415, 1.03]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[Math.PI / 2, 0, 0]} />
      </group>

      <group rotation={[-Math.PI / 2, 0, 2.24]} scale={2.23} position={[-0.356, -0.42, -2.26]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

// useGLTF.preload('models/volk_te-37_rim.glb')
